# Generated by Django 4.2.1 on 2023-07-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='bajarildi',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='foydalanuvchi',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='haqida',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='sarlavha',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
