# Generated by Django 4.2.3 on 2023-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_dob_foydalanuvchi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifalar',
            name='tugatish_muddati',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
