# Generated by Django 4.2.1 on 2023-07-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_completed_todo_bajarildi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('familiya', models.CharField(max_length=25)),
                ('pochta', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameModel(
            old_name='Todo',
            new_name='Vazifalar',
        ),
        migrations.AlterField(
            model_name='vazifalar',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.foydalanuvchi'),
        ),
    ]
