# Generated by Django 4.2 on 2023-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_vazifalar_tugatish_muddati'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='name')),
                ('last_name', models.CharField(max_length=23, verbose_name='last_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='date',
        ),
    ]
