# Generated by Django 4.2 on 2023-07-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_user_remove_foydalanuvchi_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Odam',
        ),
    ]
