# Generated by Django 4.2 on 2023-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_rename_user_odam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UquvchiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=23, verbose_name='Familiya')),
            ],
        ),
        migrations.DeleteModel(
            name='Odam',
        ),
    ]
