# Generated by Django 4.2 on 2023-07-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_uquvchimodel_delete_odam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foydalanuvchi',
            new_name='FoydalanuvchiModel',
        ),
        migrations.RenameModel(
            old_name='Vazifalar',
            new_name='VazifaModel',
        ),
    ]
