# Generated by Django 4.2 on 2023-07-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_vazifamodel_foydalanuvchi_alter_vazifamodel_sarlavha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifamodel',
            name='foydalanuvchi',
            field=models.ForeignKey(default='Muhammad', on_delete=django.db.models.deletion.CASCADE, to='to_do_list.foydalanuvchimodel'),
        ),
    ]
