# Generated by Django 4.2 on 2023-07-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0012_vazifamodel_foydalanuvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifamodel',
            name='foydalanuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.foydalanuvchimodel'),
        ),
    ]
