# Generated by Django 4.2 on 2023-07-21 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_list', '0013_alter_vazifamodel_foydalanuvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifamodel',
            name='foydalanuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
