# Generated by Django 4.2 on 2023-07-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_list', '0014_alter_vazifamodel_foydalanuvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajarildiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='vazifa')),
                ('tuliq_malumot', models.TextField()),
                ('tugatish_muddati', models.DateTimeField(blank=True, null=True)),
                ('foydalanuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoydalanuvchiModel',
        ),
    ]
