# Generated by Django 4.2 on 2023-07-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0015_bajarildimodel_delete_foydalanuvchimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajarildimodel',
            old_name='tugatish_muddati',
            new_name='tugatilgan_muddat',
        ),
        migrations.RemoveField(
            model_name='bajarildimodel',
            name='foydalanuvchi',
        ),
    ]
