# Generated by Django 4.2 on 2023-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0016_rename_tugatish_muddati_bajarildimodel_tugatilgan_muddat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBajarildiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='vazifamodel',
            name='bajarilgan_vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
