# Generated by Django 4.2 on 2023-07-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0017_datebajarildimodel_vazifamodel_bajarilgan_vaqt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BajarildiModel',
        ),
        migrations.AddField(
            model_name='vazifamodel',
            name='date_bajarildi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.datebajarildimodel'),
        ),
    ]
