# Generated by Django 4.2 on 2023-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0020_rename_bajarildgan_date_vazifamodel_bajarilgan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifamodel',
            name='bajarilgan_vaqt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
