# Generated by Django 4.2 on 2023-07-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0021_alter_vazifamodel_bajarilgan_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifamodel',
            name='boshlanish_vaqti',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
