# Generated by Django 4.2 on 2023-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0022_vazifamodel_boshlanish_vaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifamodel',
            name='boshlangan_vaqt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
