# Generated by Django 4.2 on 2023-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0023_vazifamodel_boshlangan_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vazifamodel',
            name='bajarilgan_vaqt',
        ),
        migrations.RemoveField(
            model_name='vazifamodel',
            name='boshlangan_vaqt',
        ),
        migrations.AlterField(
            model_name='vazifamodel',
            name='boshlanish_vaqti',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vazifamodel',
            name='tugatish_muddati',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
