# Generated by Django 4.2 on 2023-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0024_remove_vazifamodel_bajarilgan_vaqt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifamodel',
            name='bajarilgan_vaqt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
