# Generated by Django 4.2 on 2023-07-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0025_vazifamodel_bajarilgan_vaqt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UquvchiModel',
        ),
        migrations.AlterModelOptions(
            name='datebajarildimodel',
            options={'ordering': ['date']},
        ),
    ]
